name: Auto Merge PR on Push

on:
  push:

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Find related PR
        id: find_pr
        uses: juliangruber/find-pull-request-action@v1
        with:
          github_token: ${{ secrets.ACC_TKN }}

      - name: Merge the PR using GitHub CLI
        if: steps.find_pr.outputs.number != ''
        env:
          GH_TOKEN: ${{ secrets.ACC_TKN }}
        run: |
          echo "Merging PR #${{ steps.find_pr.outputs.number }}"
          gh pr merge ${{ steps.find_pr.outputs.number }} --squash --repo ${{ github.repository }} --delete-branch --auto
          
