name: Auto Merge Pull Requests
on:
  pull_request:
    types:
      - labeled
      - opened
      - synchronize
      - reopened
  jobs:
    automerge:
      runs-on: ubuntu-latest
      steps:
        - name: Enable auto-merge for PR
          uses: peter-evans/enable-pull-request-automerge@v3
          with:
            token: ${{ secrets.ACC_TKN }}
            merge-method: squash
