name: Auto Merge PR on PR creation

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Merge PR immediately
        if: github.event.pull_request.state == 'open'
        env:
          GH_TOKEN: ${{ secrets.ACC_TKN }}
        run: |
          pr_number=${{ github.event.pull_request.number }}
          echo "Merging PR #$pr_number"
          gh pr merge $pr_number \
            --squash \
            --delete-branch \
            --repo ${{ github.repository }} \
            --auto \
            --admin
            
